### ISSUE TITLE
how to use cgd_util.txt_to_dir?

### ISSUE THREAD

**Issue by githubarooski** [afiaka87/clip-guided-diffusion#10]
Hi, I'm trying to use cgd_util.txt_to_dir in my colab to clean up the directory names. Do you have any advice on bringing this into River's original colab? 

`ModuleNotFoundError: No module named 'cgd'`

Many thanks

**Comment by afiaka87** [comment]
@githubarooski that functionality got refactored a bit recently because I implemented multiple text prompts and image prompts. It is now called `clean_and_combine_prompts` and works on a list of prompts. If you just have one you can just wrap it in a list `[my_prompt]`

Since the code still isn't stable here and it sounds like you wanna use the original notebooks as well; perhaps you can just copy-paste this into a notebook?

```
def alphanumeric_filter(s: str) -> str:
    return re.sub(ALPHANUMERIC_REGEX, "", s).replace(" ", "_")

def clean_and_combine_prompts(base_path, txts, batch_idx, max_length=255) -> str:
    clean_txt = "_".join([alphanumeric_filter(txt) for txt in txts])[:max_length]
    return os.path.join(base_path, clean_txt, f"{batch_idx:02}")
```

**Comment by githubarooski** [comment]
Thanks for the response. This looks like similar features I'm working to integrate. It's very slow going because my python is entry level. Are you planning to publish a colab with your helper utilities?

**Comment by afiaka87** [comment]
@githubarooski I have a colab notebook for _this_ project in the root of the github repository.

It isn't yet public/stable. 

This code uses a feature of python called "generators" which are indeed a bit tough to wrap your head around.  Aside from that; a lot of this code is very "reasearch-y" because that was its original intended audience. I've done my best to strike a balance between the strange realm of research where single-letter variables are encouraged and the software engineering realm I'm used to; but I'll admit it isn't perfect.
